version: "2"

services:
  my-robohon:
    build: .
    image: robohon:0.0.1
    container_name: robohonServer
#    volumes:
#      - /c/Users/nttdata0523/robohon/:/tmp/
    ports:
      - "8080:8080" #restapi
